kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  limit-req-status-code: "429"  # Status code to return when a request exceeds the rate limit
  limit-req-zone-name: "global"  # Name of the zone referenced in ingress annotations
  limit-req-zone-size: "10m"  # Memory size allocated to the rate limiting zone
  http-snippet: |    # This sets a memory zone of 10MB, identified as `global_limit`, with a limit of 5 requests per minute per IP address
    limit_req_zone $binary_remote_addr zone=global_limit:10m rate=5r/m;
  server-snippet: |  # This sets limit_req
    limit_req zone=global_limit burst=2 nodelay;
  log-format-upstream:  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer"  "$http_user_agent" "$http_x_forwarded_for" "$http_x_client_id"'  # Custom log format to include X-Client-Id, client IP, user agent, etc.
